// <auto-generated />
using System;
using ExcuseAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExcuseAPI.Migrations
{
    [DbContext(typeof(ExcuseDbContext))]
    [Migration("20200825223828_InitialMode")]
    partial class InitialMode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExcuseAPI.Models.Excuse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Employee_Date");

                    b.Property<string>("Employee_LastName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("ExcuseTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ExcuseTypeId");

                    b.ToTable("Excuses");
                });

            modelBuilder.Entity("ExcuseAPI.Models.ExcuseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ExcusesType");
                });

            modelBuilder.Entity("ExcuseAPI.Models.Excuse", b =>
                {
                    b.HasOne("ExcuseAPI.Models.ExcuseType", "ExcuseType")
                        .WithMany()
                        .HasForeignKey("ExcuseTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
